<a href="https://colab.research.google.com/github/alison-engfis/alison-engfis/blob/main/nivel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NÍVEL DO GUAÍBA EM UM ANO

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('Dados.csv')

df.head(21)

,% year,month,day,hour,minute,second (GMT/UTC),water level (meters)
0,2023,9,14,20,40,0,2.529
1,2023,9,14,20,50,0,2.529
2,2023,9,14,21,0,0,2.529
3,2023,9,14,21,10,0,2.529
4,2023,9,14,21,20,0,2.529
5,2023,9,14,21,30,0,2.529
6,2023,9,14,21,40,0,2.529
7,2023,9,14,21,50,0,2.529
8,2023,9,14,22,0,0,2.528
9,2023,9,14,22,10,0,2.528
10,2023,9,14,22,20,0,2.527
11,2023,9,14,22,30,0,2.527
12,2023,9,14,22,40,0,2.526
13,2023,9,14,22,50,0,2.526
14,2023,9,14,23,0,0,2.525
15,2023,9,14,23,10,0,2.524
16,2023,9,14,23,20,0,2.523
17,2023,9,14,23,30,0,2.522
18,2023,9,14,23,40,0,2.521
19,2023,9,14,23,50,0,2.520
20,2023,9,15,0,0,0,2.519

In [3]:
df.tail(10)

,% year,month,day,hour,minute,second (GMT/UTC),water level (meters)
50698,2024,9,18,0,20,0,1.148
50699,2024,9,18,0,30,0,1.148
50700,2024,9,18,0,40,0,1.147
50701,2024,9,18,0,50,0,1.147
50702,2024,9,18,1,0,0,1.147
50703,2024,9,18,1,10,0,1.147
50704,2024,9,18,1,20,0,1.147
50705,2024,9,18,1,30,0,1.147
50706,2024,9,18,1,40,0,1.147
50707,2024,9,18,1,50,0,1.147

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50708 entries, 0 to 50707
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   % year                 50708 non-null  int64
 1    month                 50708 non-null  int64
 2    day                   50708 non-null  int64
 3    hour                  50708 non-null  int64
 4    minute                50708 non-null  int64
 5    second (GMT/UTC)      50708 non-null  int64
 6    water level (meters)  50708 non-null  float64
dtypes: float64(1), int64(6)
memory usage: 2.7 MB

In [5]:
df.describe()

,% year,month,day,hour,minute,second (GMT/UTC),water level (meters)
count,50708.000000,50708.000000,50708.000000,50708.000000,50708.000000,50708.0,50708.000000
mean,2023.730693,6.403881,15.849018,11.494458,25.000197,0.0,1.713039
std,0.443604,3.430057,8.898642,6.932292,17.078458,0.0,0.939621
min,2023.000000,1.000000,1.000000,0.000000,0.000000,0.0,0.456000
25%,2023.000000,3.000000,8.000000,5.000000,10.000000,0.0,1.015000
50%,2024.000000,6.000000,16.000000,11.000000,30.000000,0.0,1.387000
75%,2024.000000,9.000000,24.000000,18.000000,40.000000,0.0,2.239000
max,2024.000000,12.000000,31.000000,23.000000,50.000000,0.0,5.157000

In [6]:
df['water level (meters)'].describe()

KeyError: 'water level (meters)'

In [ ]:
df['date'] = pd.to_datetime(df['date'], format= '%d/%m/%Y %H:%M:%S')

In [ ]:
df.head(10)

In [ ]:
valor_max = 6

# Filtrar valores aceitáveis
df_limpo = df[df['water level (meters)'] <= valor_max]

In [ ]:
df.describe()

In [ ]:
# Filtrar apenas as medições realizadas às 00:00:00
df_midnight = df[df['date'].dt.hour == 0]

# Plotar gráfico
plt.figure(figsize= (10, 6))
sns.lineplot(data= df_midnight, x= 'date', y= 'water_level_meters', marker= 'o')
plt.title('Nível do Rio Guaíba às 00:00:00')
plt.xlabel('Data')
plt.ylabel('Nível da Água (metros)')
plt.grid(True)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()